import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProviderWrapper } from "@/context/authContext";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Sesame application",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<AuthProviderWrapper>
				<body className={inter.className}>
					<Navbar />
					{children}
				</body>
			</AuthProviderWrapper>
		</html>
	);
}
